### PR TITLE
docs(events): add place to click

### PR DESCRIPTION
**Pull request by Kristinita**
### 1. Summary

In header.

### 2. Argumentation

The documentation does not say, in which place user need to click. I think, non-documented actions — is not a good practice.

1. User need try to click in different places that to see effect → it may take a user time.
1. User determined where to click, but have bugs. User will try click to another places and/or more than one click, that identify expected behavior, → it may take a lot of user time.

Thanks.

### CODE REVIEW

**Comment by Skullsneeze** [comment]
Hi @Kristinita, Thanks for the feedback, and the pull request! I agree that it's a good idea to specify where the user should click in order to open the sidebar.

I noticed my flow was a bit sloppy (sorry for that), and updated my develop branch with the latest version of the master branch. Could you set the target branch for your PR to develop instead?

**Review by Skullsneeze — CHANGES_REQUESTED** [review]
Please change the target branch to develop (just updated with latest changes from master).

**Comment by Skullsneeze** [comment]
@Kristinita Also, I've just added the gutter image to this repository, so we can link to it from our own source (to prevent broken links later on)

**Comment by Kristinita** [comment]
@Skullsneeze , OK.

Thanks.

**Review by Skullsneeze — APPROVED** [review]

**Comment by Skullsneeze** [comment]
@Kristinita Thanks for the update! PR has been merged

**Pull request merged**
